### PR TITLE
Figure out the user's language and use it for wiki

### PR DESCRIPTION
**Pull request by ErezBiren**
Related to #1

### CODE REVIEW

**Comment by noam-honig** [comment]
I'm not sure this is enough to get this to work for more languages.

I personally use an english iphone but want the hebrew version of these results.

Localizing the app, would require making more changes.

I think we should park this for now, and see what users may ask - what do you think?

**Comment by ErezBiren** [comment]
Maybe we should add a settings page so the user can change it.
we could solve it with a simple combo for choosing the language in the main page
but I think it will make the main page looks too loaded

**Comment by noam-honig** [comment]
Not sure - I like the simplicity of the site.

I think that at first stage, to target only hebrew speaking users is ok

**Comment by ErezBiren** [comment]
That's fine with me.

**Pull request closed without merging**
