### PR TITLE
Add map view

### PR DESCRIPTION
**Pull request by ErezBiren**
Add tab control at the top, so we can choose list view or map view.

image

### CODE REVIEW

**Comment by ErezBiren** [comment]
@noam-honig Noam Honig

**Comment by noam-honig** [comment]
@ErezBiren 

1. Love the map
2. The tabs - not so much :) how about changing them to something more subtle in the bottom bar, next to the "more resutls in english" button - something that when you show a list it'll offer a map and vice versa?
3. Can you take a look at #11  and let me know if you think we should merge that look?

**Comment by ErezBiren** [comment]
> @ErezBiren
> 
> 1. Love the map
> 2. The tabs - not so much :) how about changing them to something more subtle in the bottom bar, next to the "more resutls in english" button - something that when you show a list it'll offer a map and vice versa?
> 3. Can you take a look at [new-look #11](https://github.com/noam-honig/wikiloc/pull/11)  and let me know if you think we should merge that look?

1. Thanks
2. sure thing, I'll do that.
3. looks pretty cool.

**Comment by noam-honig** [comment]
Note that I've merged the new look and feel, so merge it to your work

**Comment by ErezBiren** [comment]
@noam-honig fixed

image

**Comment by noam-honig** [comment]
Please test the show map on mobile - I'm worried that it'll clash with the up arrow button that is there

And let me know once it's ready for merge.

**Comment by noam-honig** [comment]
Just making sure you've marked this pull request as a "draft" pull request, so it doesn't mark it as ready for merge

Would you like for me to merge it?

**Comment by ErezBiren** [comment]
@noam-honig  -  It indeed clashes with the arrow button
what would you like to do with that?

image

**Comment by noam-honig** [comment]
אני אסדר את זה - חוץ מזה אפשר למזג?

**Comment by ErezBiren** [comment]
> אני אסדר את זה - חוץ מזה אפשר למזג?

כן

**Comment by noam-honig** [comment]
אתה גם מקבל את השגיאה הזו בDEV?
image

**Pull request merged**
