### PR TITLE
Auto scroll

### PR DESCRIPTION
**Pull request by develad**
Added results auto-fetching when the user is in the bottom of the result entry list

### CODE REVIEW

**Comment by noam-honig** [comment]
Please format the. Ode usin prettier, so there’ll be changes and it’ll be consistent to the code

**Comment by develad** [comment]
Hi Noam,
I've tried my best to set the prettier settings to be consistent with the code. 
Anyway check the functionality and tell me what you think? Yay 🎉 or Nay 👎?!

**Comment by noam-honig** [comment]
I see now that I didn't have prettier configured correctly - that's on me.

Did you test the functionality well? can I just merge it? (

**Comment by develad** [comment]
I've test it... It's working... You have a green light from me.
But it would be better if you take a look first before merging... just to get the feel of it.
I think it's a nice touch to be added to the site :)

**Comment by noam-honig** [comment]
Merging it - if anything goes wrong we'll be able to fix it

**Comment by noam-honig** [comment]
Note - that the auto scroll - scrolls everything up - I think it hinders a bit the experience.

Also - test it with different Geo locations where there are less results

**Comment by develad** [comment]
Thanks for the merge! 👍

I know it scroll everything up. I've designed it specifically that way. there are results added to the list every time there is a fetch request and those results are combined to the list by the sorting. I wanted the user to see them by scrolling back the list from the top. A little bit clunky solution but it works.

  
> Note - that the auto scroll - scrolls everything up - I think it hinders a bit the experience.
> 
> Also - test it with different Geo locations where there are less results

**Comment by noam-honig** [comment]
I think that only in the first time it adds items on top (English results)
later it adds all around

**Comment by noam-honig** [comment]
Or maybe we should just start always with hebrew and english at the same
time - and then we don't have to scroll up

**Comment by develad** [comment]
I think it would be a great and quick fix solution. That way the user can choose which of the results is the most suitable for him/her and the scrolling that trigger the fetching action will happened in the background (aka: Infinite Scroll... sort of)
Maybe later on we can add a dedicate button to filter the results between languages (En/He)

**Comment by noam-honig** [comment]
In most places there are few Hebrew results, so you usually need also the
English.

**Comment by develad** [comment]
I agree

**Pull request merged**
