### PR TITLE
Adding new ArrowUp component for smooth scrolling up the page

### PR DESCRIPTION
**Pull request by develad**
localhost_5173_wikiloc_(iPhone X) (1)

### CODE REVIEW

**Comment by noam-honig** [comment]
@develad 
Can you take a look at #11  and let me know if you think we should merge that look?

**Comment by noam-honig** [comment]
Note that on light mode it looks a bit bad - can you improve it?

image

**Comment by develad** [comment]
Sure. It's an easy fix

**Comment by noam-honig** [comment]
@develad any chance you would also like to do #12 ?

**Comment by noam-honig** [comment]
> Note that on light mode it looks a bit bad - can you improve it?
> 
> image

Also - on iphone with light mode - it displays only a black circle.

And you need to click it twice to scroll up

**Comment by develad** [comment]
> Also - on iphone with light mode - it displays only a black circle.
> 
> And you need to click it twice to scroll up

About the bugs on iPhone I really don't know what seems to be the reason for it. Maybe it would be best to open a 'Bug issue' about it?

**Comment by noam-honig** [comment]
Fixed it.

Care to think of a Better ui for the bottom bar?

**Pull request merged**
